language: node_js
node_js:
- '10'
jobs:
  include:
  - stage: build
    script: npm run tsc
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: guild-bank-bot
  on:
    repo: scip92/guild-bank-bot
